  
DROP DATABASE DESKLIT;
create DATABASE DESKLIT;
USE DESKLIT;

CREATE TABLE USER(
    ID int NOT NULL AUTO_INCREMENT,
    EMAIL varchar(255) NOT NULL,
    PASSWORD varchar(255) NOT NULL,
    ROLE varchar(255) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY unique_email (EMAIL)
);


