### Getting the full res version of a photo
GET http://localhost:80/Photos/FullRes/81f45400-9009-11ea-b24d-e7a058bc4d00.jpg
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1leHZhbmNlMDRAZ21haWwuY29tIiwiYXV0aG9yaXphdGlvbiI6ImNsaWVudCIsImlhdCI6MTU4ODg4NjA1MCwiZXhwIjoxNTg4ODg3ODUwfQ.fDU29a6fzsHBwsgWV8ZQFHnibBZRNfREYm-A6_twn4k
### getting the low res version of an image
GET http://localhost:80/Photos/LowRes/81f45400-9009-11ea-b24d-e7a058bc4d00.jpg
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1leHZhbmNlMDRAZ21haWwuY29tIiwiYXV0aG9yaXphdGlvbiI6ImNsaWVudCIsImlhdCI6MTU4ODg4NjA1MCwiZXhwIjoxNTg4ODg3ODUwfQ.fDU29a6fzsHBwsgWV8ZQFHnibBZRNfREYm-A6_twn4k
### delete photos
GET http://localhost:80/Photos/Delete/cd2eac10-90c0-11ea-9224-2dd653588a6d.jpg
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt5bGVyLmRheWJlbGw5NkBnbWFpbC5jb20iLCJhdXRob3JpemF0aW9uIjoicGhvdG9ncmFwaGVyIiwiaWF0IjoxNTg4ODk1NTc3LCJleHAiOjE1ODg4OTczNzd9.ZLqcZzPnhpXAiLpUmFTyUQB5eyzSfZi-bdzZ_HQbnjA

### Adding a client to the viewers table so that they can access a photo
POST http://localhost:80/Photos/GrantClientPermissions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJlbHlrLnBob3RvZ3JhcGh5Lmt5bGVyQGdtYWlsLmNvbSIsImF1dGhvcml6YXRpb24iOiJjbGllbnQiLCJpYXQiOjE1ODk3NDc4ODYsImV4cCI6MTU4OTc0OTY4Nn0.vjVdfC3ikGnl6WBEQoZlRh5_CObzmW3axGt47h4kdUo
Content-Type: application/json

{	
	"Email":"aquanariki@gmail.com",
    "Photo":"5715c020-986a-11ea-95da-1954bb6072b2.jpg",
    "Permission":"Low_Res"
}

### see all photos owned by the user on the token
GET http://localhost:80/Photos/MyPhotos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJlbHlrLnBob3RvZ3JhcGh5Lmt5bGVyQGdtYWlsLmNvbSIsImF1dGhvcml6YXRpb24iOiJjbGllbnQiLCJpYXQiOjE1ODk3NDc4ODYsImV4cCI6MTU4OTc0OTY4Nn0.vjVdfC3ikGnl6WBEQoZlRh5_CObzmW3axGt47h4kdUo

### see all photos shared with the user on the token
GET http://localhost:80/Client/SharedWithMe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1leHZhbmNlMDRAZ21haWwuY29tIiwiYXV0aG9yaXphdGlvbiI6ImNsaWVudCIsImlhdCI6MTU4ODg4NjA1MCwiZXhwIjoxNTg4ODg3ODUwfQ.fDU29a6fzsHBwsgWV8ZQFHnibBZRNfREYm-A6_twn4k

### Get the number of uploads left avalible to the user
GET http://localhost:80/Photos/GetUploadsLeft
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt5bGVyLmRheWJlbGw5NkBnbWFpbC5jb20iLCJhdXRob3JpemF0aW9uIjoiZnJlZSIsImlhdCI6MTU5MDA4MDUxOSwiZXhwIjoxNTkwMDgyMzE5fQ.kjIfI2NS0UlbOqbWctGOsPvjrEcdN5uO4YBI7TY1EDQ